name: "Hello World workflow"

on:
  push:
  
jobs:
  print_imprimir_date_ubuntu:
    name: Imprimindo a data no Ubundo!
    runs-on: ubuntu-latest
    
    steps:
      - name: Imprimir data ubuntu.
        run: date
  
  print_imprimir_date_windowns:
    name: Imprimindo a data no Windowns!
    runs-on: windows-latest
    
    steps:
      - name: Imprimir data Windowns.
        run: date
  
  print_imprimir_date_macos:
    name: Imprimindo a data no macos!
    runs-on: macos-latest
    
    steps:
      - name: Imprimir data macos.
        run: date
        
  print_imprimir_date_job4_depends-on:
    name: Imprimindo a data com dependencia!
    runs-on: ubuntu-latest
    needs: [print_imprimir_date_ubuntu, print_imprimir_date_windowns, print_imprimir_date_macos ]
    
    steps:
      - name: Imprimir data com dependencia.
        run: date
