name: "Hello World workflow"

on:
  push:
  
jobs:
  print_imprimir_date_ubuntu:
    name: Imprimindo a data no Ubundo!
    runs-on: ubuntu-latest
    
    steps:
      - name: Imprimir data ubuntu.
        run: date
  
  print_imprimir_date_windowns:
    name: Imprimindo a data no Windowns!
    runs-on: windows-latest
    
    steps:
      - name: Imprimir data Windowns.
        run: date
  
  print_imprimir_date_macos:
    name: Imprimindo a data no macos!
    runs-on: macos-latest
    
    steps:
      - name: Imprimir data macos.
        run: date
